In [70]:
%load_ext autoreload
%autoreload 1
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
%aimport lab2

In [110]:
f = lab2.Call_counter(lab2.f1)
x_0 = lab2.f1_0
lab2.nelde_mead(f, x_0), x_0, f.count()

(array([ 1.,  1.]), array([-1.9,  2. ]), 332)

In [111]:
lab2.hook_jeeves(lab2.f4, np.array([5,5]))

array([5, 5])

In [112]:
lab2.nelde_mead(lab2.f4, np.array([5,5]))

array([5, 5])